---
documentclass: jss
author:
  - name: Boyi Guo
    affiliation: University of Alabama at Birmingham
    # use this syntax to add text on several lines
    address: |
      | 1665 University Blvd 
      | Birmingham, AL 35294-0002   USA
    email: \email{boyiguo1@uab.edu}
    url: http://boyiguo1.github.io
  - name: Nengjun Yi
    affiliation: University of Alabama at Birmingham
    # use this syntax to add text on several lines
    address: |
      | 1665 University Blvd 
      | Birmingham, AL 35294-0002   USA
    email: \email{nyi@uab.edu}
    # To add another line, use \AND at the end of the previous one as above
title:
  formatted: "The R Package \\pkg{BHAM}: Fast and Scalable Bayeisan Hierarchical Additive Model for High-dimensional Data"
  # If you use tex in the formatted title, also supply version without
  plain:     "The R Package BHAM: Fast and Scalable Bayeisan Hierarchical Additive Model for High-dimensional Data"
  # For running headers, if needed
  short:     "\\pkg{BHAM}: Bayeisan Hierarchical Additive Model"
abstract: >
  \\pkg{BHAM} is a freely avaible R pakcage that implments Bayesian hierarchical additive models for high-dimensional clinical and genomic data. The package includes functions that generlized additive model, and Cox additive model with the spike-and-slab LASSO prior. These functions implements scalable and stable algorithms to estimate parameters. \\pkg{BHAM} also provides utility functions to construct additive models in high dimensional settings, select optimal models, summarize bi-level variable selection results, and visualize nonlinear effects. The package can facilitate flexible modeling of large-scale molecular data, i.e. detecting succeptable variables and inforing disease diagnostic and prognostic. In this article, we describe the models, algorithms and related features implemented in \\pkg{BHAM}. The package is freely avaiable via the public GitHub repository \url{https://github.com/boyiguo1/BHAM}.
keywords:
  # at least one keyword must be supplied
  formatted: [additive model, spike-and-slab LASSO, scalable]
  plain:     [additive model, spike-and-slab LASSO, scalable]
preamble: >
  \usepackage{amsmath}
output: rticles::jss_article
---

\newcommand{\pr}{\text{Pr}}
\newcommand{\bs}[1]{\boldsymbol{#1}}
\newcommand{\tp}{*}
\newcommand{\simiid}{\overset{\text{iid}}{\sim}}

```{r, setup, include=FALSE}
options(prompt = 'R> ', continue = '+ ')

library(targets)

tar_read(child_rmds)
```

```{r intro_sec, child = "01-intro.Rmd"}
```

```{r models_sec, child = "02-model.Rmd"}
```

```{r demonstration, child = "03-code.Rmd"}
```

```{r discussion, child = "04-discussion.Rmd"}
```

\clearpage
\section{Reference}
